export default {
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',

    SET_INPUT_NAME: 'SET_INPUT_NAME',
    SET_INPUT_AGE: 'SET_INPUT_AGE',
    SET_INPUT_ADDRESS: 'SET_INPUT_ADDRESS',
    SET_INPUT_TAGS: 'SET_INPUT_TAGS',
    RESET_INPUT: 'RESET_INPUT',
}